version: '3'

services:
  goapplication:
    build: .
    image: goapplication:1.0
    ports:
      - "3001:3001"
    environment:
      - fiber_port=3001
      - fiber_user=admin
      - fiber_password=12345
